import {build} from 'esbuild';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
const compiled=await build({entryPoints:['lib/share-api.ts'],bundle:true,write:false,format:'esm',platform:'node',target:'node22'});
const {shareApi}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
const sqlite=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8'));
const database={prepare(sql){return {bind(...params){const stmt=sqlite.prepare(sql);return {async first(){return stmt.get(...params)||null;},async all(){return {results:stmt.all(...params)};},async run(){return {meta:stmt.run(...params)};}};}};}};
let owner='alice';const handle=shareApi({database:()=>database,user:async()=>owner?{userId:owner}:null});
const doc={version:1,name:'한글 🏠',blocks:[{x:1,y:2,z:3,type:'oak_stairs',facing:'east'}]};
const id='a'.repeat(32),body={id,document:doc};
const request=(method,body,origin='https://example.test')=>new Request('https://example.test/api/shares',{method,headers:{origin,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});
let response=await handle(request('POST',body));assert.equal(response.status,201);assert.equal((await response.json()).path,'/share/'+id);
response=await handle(request('POST',body));assert.equal(response.status,201);assert.equal((await (await handle(request('GET'))).json()).shares.length,1);
assert.equal((await handle(request('POST',{...body,document:{...doc,name:'다른 내용'}}))).status,409);
owner='bob';assert.equal((await (await handle(request('GET'))).json()).shares.length,0);assert.equal((await handle(request('DELETE'),id)).status,404);assert.equal((await handle(request('POST',body))).status,409);
owner='';assert.equal((await handle(request('POST',{...body,id:'b'.repeat(32)}))).status,401);assert.equal((await handle(request('GET'))).status,401);assert.equal((await handle(request('DELETE'),id)).status,401);
response=await handle(request('GET'),id);assert.equal(response.status,200);const shared=await response.json();assert.deepEqual(shared.document,doc);assert(!('ownerId' in shared));assert.equal(response.headers.get('Cache-Control'),'no-store');
owner='alice';assert.equal((await handle(request('POST',body,'https://other.test'))).status,403);assert.equal((await handle(request('DELETE',undefined,'https://other.test'),id)).status,403);
assert.equal((await handle(request('POST',{id:'b'.repeat(32),document:{...doc,blocks:[{...doc.blocks[0],x:48}]}}))).status,400);
assert.equal((await handle(request('POST',{id:'b'.repeat(32),document:{...doc,blocks:[...doc.blocks,...doc.blocks]}}))).status,400);
assert.equal((await handle(request('GET'),'bad')).status,404);
assert.equal((await handle(request('POST',{...body,padding:'x'.repeat(1_800_001)}))).status,413);
for(let i=1;i<100;i++){const id=i.toString(16).padStart(32,'0');assert.equal((await handle(request('POST',{id,document:doc}))).status,201);}
assert.equal((await handle(request('POST',{id:'c'.repeat(32),document:doc}))).status,409);
assert.equal((await handle(request('DELETE'),id)).status,200);assert.equal((await handle(request('GET'),id)).status,404);assert.equal((await handle(request('DELETE'),id)).status,404);
owner='bob';assert.equal((await handle(request('POST',body))).status,409);owner='alice';
assert.equal(sqlite.prepare('SELECT snapshot FROM blueprint_shares WHERE id = ?').get(id).snapshot,'');
assert.equal((await handle(request('POST',{id:'c'.repeat(32),document:doc}))).status,201);
const plan=sqlite.prepare('EXPLAIN QUERY PLAN SELECT id FROM blueprint_shares WHERE owner_id = ? ORDER BY created_at DESC').all('alice');assert(plan.some(p=>p.detail.includes('idx_blueprint_shares_owner_created')));
sqlite.close();console.log('PASS: SQLite migrations, snapshots, idempotent creation, account isolation, anonymous preview, owner-only revocation, origin/size/bounds checks, 100-link limit and index use.');
