import {build} from 'esbuild';
import assert from 'node:assert/strict';
async function moduleAt(entry){const r=await build({entryPoints:[entry],bundle:true,write:false,format:'esm',platform:'node',target:'node22'});return import('data:text/javascript;base64,'+Buffer.from(r.outputFiles[0].text).toString('base64'));}
const e=await moduleAt('lib/editor.ts'),g=await moduleAt('lib/geometry.ts');
const empty={version:1,name:'테스트 🏠',blocks:[]};
const filled=e.regionEdit(empty,[2,2,2],[0,0,0],'fill','oak_planks','north','');assert.equal(filled.blocks.length,27);assert.equal(empty.blocks.length,0);
assert.throws(()=>e.regionEdit(empty,[0,0,0],[47,47,47],'fill','stone','north',''),/16,000/);assert.throws(()=>e.regionEdit(empty,[0.5,0,0],[1,1,1],'erase','stone','north',''));
const replaced=e.regionEdit(filled,[0,0,0],[1,1,1],'replace','stone','east','oak_planks');assert.equal(replaced.blocks.filter(b=>b.type==='stone').length,8);assert.equal(replaced.blocks.length,27);
assert(e.sameDocument(filled,e.regionEdit(filled,[0,0,0],[1,1,1],'replace','stone','north','glass')));
const erased=e.regionEdit(filled,[0,0,0],[1,1,1],'erase','stone','north','');assert.equal(erased.blocks.length,19);
const changes=e.diffBlocks(filled.blocks,replaced.blocks);assert.equal(changes.length,8);assert(changes.every(c=>c.kind==='replaced'));assert.equal(e.diffBlocks([],filled.blocks).filter(c=>c.kind==='added').length,27);assert.equal(e.diffBlocks(filled.blocks,erased.blocks).filter(c=>c.kind==='removed').length,8);
const block={x:47,y:47,z:47,type:'oak_stairs',facing:'east'};assert.equal(g.blockBoxes(block)[1][0],.5);assert.equal(g.blockBoxes({...block,facing:'west'})[1][3],.5);assert.equal(g.blockBoxes({...block,type:'oak_slab',facing:'up'})[0][1],.5);assert(!g.isFullCube(block));assert(g.isFullCube({...block,type:'stone'}));
for(const blocks of [[],[block],[{...block,x:0,y:0,z:0},block],filled.blocks]){const camera=g.fitCamera(blocks,800,600);assert(Number.isFinite(camera.zoom)&&camera.zoom>0);for(const b of blocks)for(const dx of [0,1])for(const dy of [0,1])for(const dz of [0,1]){const x=b.x+dx-camera.center[0],y=b.y+dy-camera.center[1],z=b.z+dz-camera.center[2],u=x*Math.cos(camera.angle)-z*Math.sin(camera.angle),v=x*Math.sin(camera.angle)+z*Math.cos(camera.angle);assert(Math.abs(u*camera.zoom)<=335.001);assert(Math.abs((v*Math.sin(camera.pitch)-y*Math.cos(camera.pitch))*camera.zoom)<=225.001);}}
const progress=e.emptyProgress();progress.done=['placed:oak_planks:27'];progress.choices.recipes.oak_planks='gather';progress.layers[0]=e.layerSignature(filled.blocks,0);
const entry={id:'test',document:filled,progress,updated:''};const library={version:1,active:'test',entries:[entry]};assert.deepEqual(e.readLibrary(JSON.parse(JSON.stringify(library))),library);assert.throws(()=>e.readLibrary({...library,active:'missing'}));assert.throws(()=>e.readLibrary({...library,entries:[entry,entry]}));assert.throws(()=>e.readLibrary({...library,entries:[{...entry,progress:{...progress,done:[1]}}]}));
assert.equal(e.layerSignature([...filled.blocks].reverse(),0),progress.layers[0]);assert.notEqual(e.layerSignature(replaced.blocks,0),progress.layers[0]);assert.equal(e.layerSignature(replaced.blocks,2),e.layerSignature(filled.blocks,2));
let state={entry,history:{undo:[],redo:[]}};state=e.recordEdit(state.entry,{...filled,name:'이름 수정'},state.history);assert.equal(state.history.undo.length,1);state=e.travelHistory(state.entry,state.history);assert.equal(state.entry.document.name,filled.name);assert.deepEqual(state.entry.progress,progress);state=e.travelHistory(state.entry,state.history,true);assert.equal(state.entry.document.name,'이름 수정');
state=e.recordEdit(state.entry,{...replaced,name:state.entry.document.name},state.history);assert.equal(state.history.undo.length,2);state=e.travelHistory(state.entry,state.history);assert.equal(state.entry.document.blocks.filter(b=>b.type==='stone').length,0);const before=state.history;state=e.recordEdit(state.entry,{...state.entry.document,blocks:[...state.entry.document.blocks].reverse()},state.history);assert.equal(state.history,before);assert.equal(state.history.redo.length,1);
state=e.recordEdit(state.entry,{...erased,name:'다른 작업'},state.history);assert.equal(state.history.redo.length,0);for(let i=0;i<50;i++)state=e.recordEdit(state.entry,{...state.entry.document,name:`수정 ${i}`},state.history);assert.equal(state.history.undo.length,40);
console.log('PASS: atomic region edits, limits, filtered replacement, diff classification, shapes, fitted camera bounds, library/progress round trip, invalid restore rejection, layer invalidation, rename/region undo, no-op and 40-step history.');
