'use client';
import {useMemo,useRef,useState} from 'react';
import {BookOpen,BrickWall,Check,ChevronLeft,ChevronRight,Minus,Plus,Search,X} from 'lucide-react';
import {catalogMeta,Item,itemName,items,matchesItem,methodLabels,placeableItems,placementById,recipesByItem,specialRecipeItems} from '../lib/catalog';
const PAGE_SIZE=60;
function Swatch({item}:{item:Item}){return <span className="voxel" style={{'--block':item.color} as React.CSSProperties}/>;}
function Pager({page,setPage,total}:{page:number;setPage:(n:number)=>void;total:number}){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));return <div className="catalog-pager"><button aria-label="이전 페이지" disabled={!page} onClick={()=>setPage(page-1)}><ChevronLeft size={15}/></button><span>{page+1} / {pages} · {total.toLocaleString()}종</span><button aria-label="다음 페이지" disabled={page>=pages-1} onClick={()=>setPage(page+1)}><ChevronRight size={15}/></button></div>;}
export function ItemDictionary({onPlace}:{onPlace:(id:string)=>void}){
 const ref=useRef<HTMLDialogElement>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[selected,setSelected]=useState<Item|null>(null);
 const found=useMemo(()=>items.filter(i=>matchesItem(i,query)&&(filter==='all'||(filter==='placeable'?!!i.placement:!i.placement))),[query,filter]);
 return <><button className="dictionary-trigger" onClick={()=>ref.current?.showModal()}><BookOpen size={15}/>전체 아이템 사전 <span>{catalogMeta.items.toLocaleString()}</span></button><dialog ref={ref} className="dictionary-dialog"><div className="dictionary-heading"><div><h2>Java 26.2 아이템 사전</h2><p>전체 {catalogMeta.items.toLocaleString()}종 · 설치 가능 {catalogMeta.placeable.toLocaleString()}종</p></div><button aria-label="아이템 사전 닫기" onClick={()=>ref.current?.close()}><X size={20}/></button></div>
 <label className="search"><Search size={16}/><input aria-label="전체 아이템 검색" placeholder="한국어 이름 또는 영문 ID 검색" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><div className="categories">{[['all','전체'],['placeable','설치 가능'],['other','설치 불가']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>{setFilter(id);setPage(0);}}>{label}</button>)}</div>
 <div className="dictionary-body"><div className="dictionary-results">{found.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE).map(i=><button key={i.id} className={selected?.id===i.id?'selected':''} onClick={()=>setSelected(i)}><span className="mini-block" style={{background:i.color}}/><span>{i.name}<small>{i.id}</small></span><em>{i.placement?'설치':'재료·아이템'}</em></button>)}{!found.length&&<p className="empty">검색 결과가 없습니다.</p>}</div><div className="dictionary-info">{selected?<><h3>{selected.name}</h3><code>minecraft:{selected.id}</code><p>{selected.english}</p><p>{selected.placement?selected.placement.kind==='entity'?'설치 가능한 엔티티':selected.placement.kind==='fluid'?'설치 가능한 유체':'설치 가능한 블록':'설치 불가능 아이템'} · 최대 {selected.stack}개 / 칸</p>{selected.placement&&<button className="primary" onClick={()=>{onPlace(selected.placement!.id);ref.current?.close();}}>팔레트에서 선택</button>}<h4>제작법</h4>{(recipesByItem.get(selected.id)||[]).map(r=><div className="dictionary-recipe" key={r.id}><strong>{methodLabels[r.method]||r.method} → {r.count}개</strong><ul>{r.ingredients.map((i,n)=><li key={n}>{i.options.length===1?itemName(i.options[0]):`${itemName(i.options[0])} 등 ${i.options.length}종 중 선택`} × {i.count}{i.options.length>1&&<details><summary>대체 재료 보기</summary>{i.options.map(itemName).join(', ')}</details>}</li>)}</ul></div>)}{!(recipesByItem.get(selected.id)||[]).length&&<p>{specialRecipeItems.has(selected.id)?'아이템 상태에 따라 달라지는 특수 제작법입니다. 직접 준비 수량으로 계산합니다.':'고정 제작법이 없습니다. 채집·거래·전리품 또는 크리에이티브 모드에서 준비하세요.'}</p>}</>:<p className="empty">아이템을 선택하면 설치 여부와 제작법을 볼 수 있습니다.</p>}</div></div><Pager page={page} setPage={setPage} total={found.length}/><p className="catalog-note">소환 알·투사체는 설치물에서 제외합니다. 설치물은 설계용 단순 형상으로 표시합니다.</p></dialog></>;
}
export default function BlockPalette({selected,onSelect,facing,onFacing,onPlaceAt,onEraseAt}:{selected:string;onSelect:(id:string)=>void;facing:string;onFacing:(s:string)=>void;onPlaceAt:(coords:number[])=>void;onEraseAt:(coords:number[])=>void}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('전체'),[page,setPage]=useState(0),[coords,setCoords]=useState([14,1,20]);const item=placementById.get(selected);
 const found=useMemo(()=>placeableItems.filter(i=>matchesItem(i,query)&&(category==='전체'||i.category===category)),[query,category]);
 return <aside className="palette-panel"><div className="panel-heading"><h2><BrickWall size={17}/>블록 팔레트</h2><span>{catalogMeta.placeable.toLocaleString()}</span></div><small className="catalog-version">Java Edition 26.2 · 설치 가능한 항목</small><label className="search"><Search size={16}/><input aria-label="설치물 검색" placeholder="이름 또는 ID 검색…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><div className="categories catalog-categories">{['전체','건축','자연','레드스톤','장식','설치물'].map(c=><button className={category===c?'active':''} key={c} onClick={()=>{setCategory(c);setPage(0);}}>{c}</button>)}</div><div className="block-grid">{found.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE).map(i=><button key={i.id} title={`${i.name} · ${i.id}`} className={'block-tile '+(selected===i.placement!.id?'selected':'')} onClick={()=>onSelect(i.placement!.id)}><Swatch item={i}/><span>{i.name}</span>{selected===i.placement!.id&&<Check size={12} className="selected-check"/>}</button>)}</div>{!found.length&&<p className="empty">검색 결과가 없습니다.</p>}<Pager page={page} setPage={setPage} total={found.length}/><ItemDictionary onPlace={onSelect}/>
 <div className="selection"><small>선택한 설치물</small><strong>{item?.name}</strong><code>minecraft:{item?.id}</code>{item?.id!==selected&&<small>설치 후: {selected}</small>}<label>방향<select value={facing} onChange={e=>onFacing(e.target.value)}>{[['north','북쪽'],['south','남쪽'],['east','동쪽'],['west','서쪽'],['up','위'],['down','아래']].map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label><div className="coordinate-inputs">{['X','Y','Z'].map((a,i)=><label key={a}>{a}<input type="number" min={0} max={47} value={coords[i]} onChange={e=>setCoords(v=>v.map((n,j)=>i===j?Number(e.target.value):n))}/></label>)}</div><div className="row"><button onClick={()=>onPlaceAt(coords)}><Plus size={14}/>배치</button><button onClick={()=>onEraseAt(coords)}><Minus size={14}/>삭제</button></div></div></aside>;
}
