'use client';
import {useMemo,useState} from 'react';
import {Choices,choiceKey,materialPlan,MaterialNode,recipeLabel,requiredItems} from '../lib/materials';
import {itemById,itemName,methodLabels,recipesByItem,stackText} from '../lib/catalog';
import {Progress} from '../lib/editor';
export default function MaterialsPanel({blocks,progress,onProgress}:{blocks:{type:string}[];progress:Progress;onProgress:(fn:(p:Progress)=>Progress)=>void}){
 const {choices,done}=progress;const [expand,setExpand]=useState(true);
 const setChoices=(value:Choices|((v:Choices)=>Choices))=>onProgress(p=>({...p,choices:typeof value==='function'?value(p.choices):value}));
 const setDone=(value:string[]|((v:string[])=>string[]))=>onProgress(p=>({...p,done:typeof value==='function'?value(p.done):value}));
 const required=useMemo(()=>requiredItems(blocks),[blocks]);
 const computed=useMemo(()=>{try{return {plan:materialPlan(required,choices),error:''};}catch(e){return {plan:null,error:(e as Error).message};}},[required,choices]);const plan=computed.plan;
 function toggle(id:string){setDone(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);}
 function route(n:MaterialNode){const options=recipesByItem.get(n.id)||[];if(!options.length)return <small className="catalog-note">채집·거래·전리품 등으로 준비</small>;return <label className="recipe-route">준비 방법<select aria-label={`${itemName(n.id)} 준비 방법`} value={choices.recipes[n.id]??n.recipe?.id??'gather'} onChange={e=>{setChoices(v=>({...v,recipes:{...v.recipes,[n.id]:e.target.value}}));setDone([]);}}><option value="gather">직접 준비</option>{options.map(r=><option key={r.id} value={r.id}>{methodLabels[r.method]||r.method} · {recipeLabel(r)}</option>)}</select></label>;}
 return <div className="materials-scroll"><div className="material-summary"><small>필요한 설치 아이템</small><div>{blocks.length.toLocaleString()}<span>개 · {required.length}종</span></div><p>설치 수량과 제작에 필요한 재료를 함께 확인하세요.</p></div><div className="material-list">{required.map(({id,count})=>{const i=itemById.get(id)!;const token=`placed:${id}:${count}`;return <label key={id} className={done.includes(token)?'completed':''}><input type="checkbox" checked={done.includes(token)} onChange={()=>toggle(token)}/><span className="mini-block" style={{background:i.color}}/><span className="material-name">{i.name}<small>{stackText(id,count)}</small></span><b>{count.toLocaleString()}</b></label>;})}{!required.length&&<p className="empty">아직 설치물이 없습니다.</p>}</div>
 <label className="submaterial-toggle"><input type="checkbox" checked={expand} onChange={e=>setExpand(e.target.checked)}/>하위 재료 함께 보기</label>
 {expand&&!!required.length&&<div className="craft-plan"><div className="craft-heading"><h3>기초 재료 합계</h3><button onClick={()=>{setChoices({recipes:{},ingredients:{}});setDone([]);}}>계산 초기화</button></div><p className="catalog-note">선택한 제작법의 마지막 재료입니다. 같은 재료는 합산하고, 조합 단위에 맞춰 올림 계산합니다.</p>{computed.error&&<p role="alert">{computed.error}</p>}
 {plan?.base.map(n=>{const token=`base:${n.id}:${n.required}`;return <div className="base-material" key={n.id}><label><input type="checkbox" checked={done.includes(token)} onChange={()=>toggle(token)}/><span>{itemName(n.id)}</span><b>{n.required.toLocaleString()}개</b></label><small>{stackText(n.id,n.required)}</small>{n.reason&&<p className="catalog-note">{n.reason}</p>}{route(n)}</div>;})}
 {!!plan?.steps.length&&<><h3>제작 단계와 하위 재료</h3><p className="catalog-note">아래에서 위로 제작하세요. 수량은 설계도 전체를 합산한 값입니다.</p>{plan.steps.map(n=><details className="craft-step" key={n.id} open><summary>{itemName(n.id)}<span>{n.required.toLocaleString()}개 필요</span></summary>{route(n)}<p className="craft-yield">{n.recipe!.count}개씩 × {n.batches.toLocaleString()}회 → {n.produced.toLocaleString()}개{n.surplus>0&&<strong> · {n.surplus.toLocaleString()}개 남음</strong>}</p><ul>{n.ingredients.map(i=><li key={i.slot}>{i.options.length>1?<select aria-label={`${itemName(n.id)} 대체 재료 ${i.slot+1}`} value={i.id} onChange={e=>{setChoices(v=>({...v,ingredients:{...v.ingredients,[choiceKey(n.recipe!,i.slot)]:e.target.value}}));setDone([]);}}>{i.options.map(id=><option key={id} value={id}>{itemName(id)}</option>)}</select>:<span>{itemName(i.id)}</span>}<b>× {(i.count*n.batches).toLocaleString()}</b></li>)}</ul></details>)}</>}
 {plan?.warnings.map(w=><p className="plan-warning" key={w}>{w}</p>)}{!!plan?.heatBatches&&<p className="catalog-note">가열 {plan.heatBatches}회 · 연료는 종류에 따라 효율이 달라 합계에서 제외했습니다.</p>}{!!plan?.returned.length&&<p className="catalog-note">조합 후 반환: {plan.returned.map(r=>`${itemName(r.id)} ${r.count}개`).join(', ')}. 다시 채우는 작업은 직접 진행하세요.</p>}<p className="catalog-note">유체·엔티티도 배치 1곳당 아이템 1개로 계산합니다. 복제·상태 의존 특수 제작법과 월드 내 변환은 자동 분해하지 않습니다.</p></div>}
 </div>;
}
