'use client';
import {useEffect,useRef,useState} from 'react';
import {Blueprint} from '../lib/blueprint';
type Shared={id:string;name:string;blockCount:number;createdAt:string};
export default function SharePanel({doc}:{doc:Blueprint}){
 const [shares,setShares]=useState<Shared[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[signIn,setSignIn]=useState(false),[url,setUrl]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState('');
 const attempt=useRef<{id:string;document:Blueprint}|null>(null);
 async function refresh(signal?:AbortSignal){setLoading(true);try{const r=await fetch('/api/shares',{signal,cache:'no-store'}),data=await r.json() as {error?:string;shares:Shared[];path:string};if(!r.ok){setSignIn(r.status===401);throw Error(data.error||'공유 목록을 불러오지 못했습니다.');}setShares(data.shares);setSignIn(false);setError('');}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{const controller=new AbortController();void refresh(controller.signal);return()=>controller.abort();},[]);
 async function create(){if(busy)return;setBusy(true);setError('');try{if(!attempt.current||attempt.current.document!==doc)attempt.current={id:crypto.randomUUID().replaceAll('-',''),document:doc};const r=await fetch('/api/shares',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(attempt.current)}),data=await r.json() as {error?:string;shares:Shared[];path:string};if(!r.ok){setSignIn(r.status===401);throw Error(data.error||'공유 링크를 만들지 못했습니다.');}setUrl(new URL(data.path,location.origin).href);setNotice('공유 시점의 설계도를 저장했습니다.');attempt.current=null;await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function revoke(id:string){setBusy(true);setError('');try{const r=await fetch(`/api/shares/${id}`,{method:'DELETE'}),data=await r.json() as {error?:string;shares:Shared[];path:string};if(!r.ok)throw Error(data.error);setShares(v=>v.filter(s=>s.id!==id));if(url.endsWith('/'+id))setUrl('');setConfirm('');setNotice('공유 링크를 해제했습니다. 이미 복사한 설계도는 유지됩니다.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function copy(value:string){setUrl(value);try{await navigator.clipboard.writeText(value);setNotice('링크를 복사했습니다.');}catch{setNotice('아래 링크를 선택해 직접 복사하세요.');}}
 return <><h2>링크로 공유하기</h2><p><strong>{doc.name}</strong> · {doc.blocks.length.toLocaleString()} 블록</p><p>현재 설계도의 사본을 저장합니다. 원본을 수정해도 이 링크의 내용은 바뀌지 않습니다. 링크를 받은 사람은 사이트 접근 권한 안에서 설계도를 보고 복사할 수 있습니다.</p>{signIn?<a className="share-sign-in" href="/signin-with-chatgpt?return_to=%2F" target="_top">로그인하고 공유하기</a>:<button className="primary" disabled={busy||loading} onClick={create}>{busy?'처리 중…':'현재 설계도 링크 만들기'}</button>}{url&&<div className="share-result"><label>공유 링크<input readOnly value={url} onFocus={e=>e.target.select()}/></label><div className="row"><button onClick={()=>copy(url)}>링크 복사</button><a href={url} target="_blank" rel="noreferrer">미리보기 열기</a></div>{/^https?:\/\/(localhost|127\.0\.0\.1)(:|\/)/.test(url)&&<p>로컬 테스트 링크입니다. 다른 기기에 보내려면 배포된 사이트에서 링크를 만드세요.</p>}</div>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}<h3>내가 만든 공유 링크</h3><button disabled={busy||loading} onClick={()=>refresh()}>목록 새로고침</button>{loading?<p>불러오는 중…</p>:<div className="library-list">{shares.map(s=><article key={s.id}><strong>{s.name}</strong><small>{s.blockCount.toLocaleString()} 블록 · {new Date(s.createdAt).toLocaleString('ko-KR')}</small><div className="row"><button disabled={busy} onClick={()=>copy(new URL(`/share/${s.id}`,location.origin).href)}>링크 복사</button><a href={`/share/${s.id}`} target="_blank" rel="noreferrer">미리보기</a><button disabled={busy} onClick={()=>setConfirm(s.id)}>공유 해제</button></div>{confirm===s.id&&<p>이 링크를 더 이상 열 수 없게 할까요?<button disabled={busy} onClick={()=>revoke(s.id)}>해제 확인</button><button disabled={busy} onClick={()=>setConfirm('')}>취소</button></p>}</article>)}{!shares.length&&!error&&<p>아직 만든 링크가 없습니다.</p>}</div>}</>;
}
