'use client';
import {useEffect,useRef,useState} from 'react';
import {Block,key} from '../lib/blueprint';
import {placementById} from '../lib/catalog';
import {Change} from '../lib/editor';
import {blockBoxes,fitCamera,isFullCube} from '../lib/geometry';
type Face={points:number[][];depth:number;block:Block;normal:number[];color:string;change?:Change['kind']};
const colors={added:'#63e695',removed:'#ff737d',replaced:'#ffd166'};
export default function Viewport({blocks,tool,layer,layerOnly,onEdit,reset,changes=[]}:{blocks:Block[];tool:string;layer:number;layerOnly:boolean;onEdit:(b:Block,normal:number[])=>void;reset:number;changes?:Change[]}){
 const ref=useRef<HTMLCanvasElement>(null),faces=useRef<Face[]>([]),drag=useRef<{x:number;y:number;ox:number;oy:number;moved:boolean;button:number}|null>(null);
 const [camera,setCamera]=useState(()=>fitCamera(blocks,800,600)),[error,setError]=useState('');
 const content=useRef(blocks);content.current=[...blocks,...changes.map(c=>c.block)];
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const r=canvas.getBoundingClientRect();setCamera(fitCamera(content.current,r.width,r.height));},[reset]);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;
 const draw=()=>{const r=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio,2);canvas.width=r.width*ratio;canvas.height=r.height*ratio;const ctx=canvas.getContext('2d');if(!ctx){setError('이 브라우저에서 캔버스를 사용할 수 없습니다.');return;}ctx.scale(ratio,ratio);
 const {angle:a,pitch:p,zoom:s,center}=camera,ca=Math.cos(a),sa=Math.sin(a),cp=Math.cos(p),sp=Math.sin(p);
 const project=(x:number,y:number,z:number)=>{x-=center[0];y-=center[1];z-=center[2];const u=x*ca-z*sa,v=x*sa+z*ca;return [r.width/2+u*s+camera.panX,r.height/2+(v*sp-y*cp)*s+camera.panY,v*cp+y*sp];};
 ctx.strokeStyle='#70877725';ctx.lineWidth=1;for(let i=0;i<=48;i++)for(const line of [[[i,0,0],[i,0,48]],[[0,0,i],[48,0,i]]]){ctx.beginPath();line.forEach((q,j)=>{const v=project(q[0],q[1],q[2]);if(j)ctx.lineTo(v[0],v[1]);else ctx.moveTo(v[0],v[1]);});ctx.stroke();}
 const changed=new Map(changes.map(c=>[key(c.block),c])),display=new Map(blocks.map(b=>[key(b),b]));for(const c of changes)display.set(key(c.block),c.block);
 const visible=[...display.values()].filter(b=>layer===-1||(layerOnly?b.y===layer:b.y<=layer)),occupied=new Map(visible.map(b=>[key(b),b])),list:Face[]=[];
 const specs=[{n:[0,1,0],v:[[0,1,0],[0,1,1],[1,1,1],[1,1,0]],shade:1.12},{n:[1,0,0],v:[[1,0,0],[1,1,0],[1,1,1],[1,0,1]],shade:.83},{n:[-1,0,0],v:[[0,0,1],[0,1,1],[0,1,0],[0,0,0]],shade:.72},{n:[0,0,1],v:[[1,0,1],[1,1,1],[0,1,1],[0,0,1]],shade:.92},{n:[0,0,-1],v:[[0,0,0],[0,1,0],[1,1,0],[1,0,0]],shade:.67}];
 for(const b of visible){const change=changed.get(key(b))?.kind,color=change?colors[change]:placementById.get(b.type)?.color||'#8b9793';for(const box of blockBoxes(b))for(const f of specs){if(f.n[0]*sa*cp+f.n[1]*sp+f.n[2]*ca*cp<=0)continue;const neighbor=occupied.get(`${b.x+f.n[0]},${b.y+f.n[1]},${b.z+f.n[2]}`);if(!change&&isFullCube(b)&&neighbor&&isFullCube(neighbor)&&changed.get(key(neighbor))?.kind!=='removed')continue;
 const points=f.v.map(v=>project(b.x+box[0]+v[0]*(box[3]-box[0]),b.y+box[1]+v[1]*(box[4]-box[1]),b.z+box[2]+v[2]*(box[5]-box[2]))),rgb=[1,3,5].map(i=>Math.min(255,Math.round(parseInt(color.slice(i,i+2),16)*f.shade)));list.push({points,depth:points.reduce((n,q)=>n+q[2],0)/4,block:b,normal:f.n,color:`rgb(${rgb.join(',')})`,change});}}
 list.sort((a,b)=>a.depth-b.depth);faces.current=list;
 const path=(f:Face)=>{ctx.beginPath();f.points.forEach((q,i)=>i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1]));ctx.closePath();};
 for(const f of list){path(f);ctx.globalAlpha=f.change==='removed'?.35:1;ctx.fillStyle=f.color;ctx.fill();ctx.strokeStyle='#15271f55';ctx.lineWidth=.65;ctx.stroke();ctx.globalAlpha=1;
 if(['oak_planks','spruce_planks','bricks'].includes(f.block.type)){const [a,b,c,d]=f.points;ctx.beginPath();ctx.moveTo((a[0]+b[0])/2,(a[1]+b[1])/2);ctx.lineTo((c[0]+d[0])/2,(c[1]+d[1])/2);ctx.stroke();}
 if(/_log$|_wood$|_stem$|_hyphae$/.test(f.block.type)){const facing=f.block.facing||'north',axis=['east','west'].includes(facing)?0:['north','south'].includes(facing)?2:1,end=Math.abs(f.normal[axis])===1,center=f.points.reduce((a,q)=>[a[0]+q[0]/4,a[1]+q[1]/4],[0,0]);ctx.strokeStyle='#31200f88';for(const t of (end?[.45,.75]:[.3,.65])){ctx.beginPath();if(end){f.points.forEach((q,i)=>{const x=center[0]+(q[0]-center[0])*t,y=center[1]+(q[1]-center[1])*t;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.closePath();}else{const [a,b,c,d]=f.points;ctx.moveTo(a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t);ctx.lineTo(d[0]+(c[0]-d[0])*t,d[1]+(c[1]-d[1])*t);}ctx.stroke();}}
 }
 for(const f of list.filter(f=>f.change)){path(f);ctx.strokeStyle=colors[f.change!];ctx.lineWidth=1.8;ctx.setLineDash(f.change==='removed'?[4,3]:[]);ctx.stroke();}ctx.setLineDash([]);
 };draw();const ro=new ResizeObserver(draw);ro.observe(canvas);return()=>ro.disconnect();},[blocks,camera,layer,layerOnly,changes]);
 function pick(x:number,y:number){const ctx=ref.current?.getContext('2d');if(!ctx)return;for(const f of [...faces.current].reverse()){const path=new Path2D();f.points.forEach((q,i)=>i?path.lineTo(q[0],q[1]):path.moveTo(q[0],q[1]));path.closePath();ctx.save();ctx.resetTransform();const hit=ctx.isPointInPath(path,x,y);ctx.restore();if(hit){onEdit(f.block,f.normal);return;}}
 const c=ref.current!.getBoundingClientRect(),u=(x-c.width/2-camera.panX)/camera.zoom,h=layer<0?0:layer,v=((y-c.height/2-camera.panY)/camera.zoom+(h-camera.center[1])*Math.cos(camera.pitch))/Math.sin(camera.pitch),bx=Math.floor(u*Math.cos(camera.angle)+v*Math.sin(camera.angle)+camera.center[0]),bz=Math.floor(-u*Math.sin(camera.angle)+v*Math.cos(camera.angle)+camera.center[2]);onEdit({x:bx,y:h-1,z:bz,type:'air'},[0,1,0]);}
 return <><canvas ref={ref} aria-label="3D 설계도. 드래그로 회전, 휠로 확대, Shift 드래그로 이동." onContextMenu={e=>e.preventDefault()} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,ox:e.clientX,oy:e.clientY,moved:false,button:e.button};}} onPointerMove={e=>{const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;d.moved ||= Math.hypot(e.clientX-d.ox,e.clientY-d.oy)>4;if(d.moved)setCamera(c=>d.button===2||e.shiftKey?{...c,panX:c.panX+dx,panY:c.panY+dy}:{...c,angle:c.angle+dx*.008,pitch:Math.max(.15,Math.min(1.5,c.pitch+dy*.008))});d.x=e.clientX;d.y=e.clientY;}} onPointerUp={e=>{const d=drag.current;drag.current=null;if(d&&!d.moved&&d.button===0&&tool!=='orbit'&&!changes.length){const r=e.currentTarget.getBoundingClientRect();pick(e.clientX-r.left,e.clientY-r.top);}}} onPointerCancel={()=>drag.current=null} onWheel={e=>setCamera(c=>({...c,zoom:Math.min(65,Math.max(.5,c.zoom*(e.deltaY>0?.92:1.08)))}))}/>{error&&<p>{error}</p>}{!!changes.length&&<div className="preview-badge">AI 미리보기 · 적용 또는 취소 후 편집</div>}<div className="zoom-controls"><button aria-label="축소" onClick={()=>setCamera(c=>({...c,zoom:Math.max(.5,c.zoom*.8)}))}>−</button><span>{Math.round(camera.zoom/22*100)}%</span><button aria-label="확대" onClick={()=>setCamera(c=>({...c,zoom:Math.min(65,c.zoom*1.25)}))}>+</button></div></>;
}
