'use client';
import {useState} from 'react';
import {Block,Blueprint} from '../lib/blueprint';
import {Entry,Library,layerSignature,regionEdit} from '../lib/editor';
import {placementById} from '../lib/catalog';
import {requiredItems} from '../lib/materials';
export function RegionPanel({doc,selected,facing,onApply}:{doc:Blueprint;selected:string;facing:string;onApply:(d:Blueprint)=>void}){
 const [from,setFrom]=useState([0,0,0]),[to,setTo]=useState([0,0,0]),[action,setAction]=useState('fill'),[replace,setReplace]=useState(''),[error,setError]=useState('');
 const types=[...new Set(doc.blocks.map(b=>b.type))];const volume=from.reduce((n,v,i)=>n*(Math.abs(v-to[i])+1),1);
 return <details className="region-panel"><summary>영역 편집</summary><p>선택한 블록: {placementById.get(selected)?.name} · {facing}</p>{[['시작',from,setFrom],['끝',to,setTo]].map(([label,values,setter])=><fieldset key={label as string}><legend>{label as string} 좌표</legend><div className="region-coords">{['X','Y','Z'].map((axis,i)=><label key={axis}>{axis}<input aria-label={`${label} ${axis}`} type="number" min={0} max={47} value={(values as number[])[i]} onChange={e=>(setter as typeof setFrom)(v=>v.map((n,j)=>j===i?Number(e.target.value):n))}/></label>)}</div></fieldset>)}<label>작업<select value={action} onChange={e=>setAction(e.target.value)}><option value="fill">채우기 (기존 블록 덮어쓰기)</option><option value="erase">영역 삭제</option><option value="replace">재료 교체 (빈 공간 유지)</option></select></label>{action==='replace'&&<label>교체할 재료<select value={replace} onChange={e=>setReplace(e.target.value)}><option value="">영역 내 모든 재료</option>{types.map(t=><option key={t} value={t}>{placementById.get(t)?.name}</option>)}</select></label>}<p>{volume.toLocaleString()}칸 · 작업 전체를 한 번에 실행 취소할 수 있습니다.</p><button onClick={()=>{try{const next=regionEdit(doc,from,to,action,selected,facing,replace);setError('');onApply(next);}catch(e){setError((e as Error).message);}}}>영역에 적용</button>{error&&<p role="alert">{error}</p>}</details>;
}
export function LibraryPanel({library,onOpen,onDuplicate,onDelete,onRestore}:{library:Library;onOpen:(id:string)=>void;onDuplicate:(e:Entry)=>void;onDelete:(id:string)=>void;onRestore:(input:unknown)=>void}){
 const [deleting,setDeleting]=useState(''),[pending,setPending]=useState<unknown>(null),[error,setError]=useState('');
 function backup(){const url=URL.createObjectURL(new Blob([JSON.stringify(library)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`blockcraft-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><h2>설계도 보관함</h2><p>이 브라우저에 자동 저장됩니다. 파일 백업에는 모든 설계도와 준비 상태가 포함됩니다.</p><div className="library-list">{library.entries.map(e=><article key={e.id}><strong>{e.document.name}{e.id===library.active?' · 작업 중':''}</strong><small>{e.document.blocks.length.toLocaleString()} 블록</small><div className="row"><button disabled={e.id===library.active} onClick={()=>onOpen(e.id)}>열기</button><button onClick={()=>onDuplicate(e)}>복제</button><button onClick={()=>setDeleting(e.id)}>삭제</button></div>{deleting===e.id&&<p>이 설계도를 삭제할까요? <button onClick={()=>{onDelete(e.id);setDeleting('');}}>삭제 확인</button><button onClick={()=>setDeleting('')}>취소</button></p>}</article>)}</div><button onClick={backup}>전체 파일 백업</button><label>백업 파일 복원<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>100_000_000)throw Error('100MB 이하의 백업 파일을 선택하세요.');setPending(JSON.parse(await f.text()));setError('');}catch(e){setError((e as Error).message);}}}/></label>{pending!==null&&<p>현재 보관함 전체를 파일 내용으로 교체합니다. 필요한 경우 먼저 백업하세요.<button onClick={()=>{try{onRestore(pending);setPending(null);setError('');}catch(e){setError((e as Error).message);}}}>복원 확인</button><button onClick={()=>setPending(null)}>취소</button></p>}{error&&<p role="alert">{error}</p>}</>;
}
export function BuildGuide({blocks,completed,onComplete}:{blocks:Block[];completed:Record<string,string>;onComplete:(y:number,signature:string)=>void}){
 const [y,setY]=useState(0),[focus,setFocus]=useState<Block|null>(null);const cells=blocks.filter(b=>b.y===y),map=new Map(cells.map(b=>[`${b.x},${b.z}`,b]));
 const minX=cells.length?Math.min(...cells.map(b=>b.x)):0,maxX=cells.length?Math.max(...cells.map(b=>b.x)):15,minZ=cells.length?Math.min(...cells.map(b=>b.z)):0,maxZ=cells.length?Math.max(...cells.map(b=>b.z)):15;
 const types=[...new Set(cells.map(b=>b.type))],signature=layerSignature(blocks,y);const count=Array.from({length:48},(_,i)=>i).filter(i=>blocks.some(b=>b.y===i)&&completed[i]===layerSignature(blocks,i)).length;
 return <div className="build-guide"><h2>층별 건축 가이드</h2><div className="guide-controls"><button disabled={y===0} onClick={()=>{setY(y-1);setFocus(null);}}>이전 층</button><label>Y <input aria-label="가이드 층" type="number" min={0} max={47} value={y} onChange={e=>{setY(Math.max(0,Math.min(47,Math.floor(Number(e.target.value)))));setFocus(null);}}/></label><button disabled={y===47} onClick={()=>{setY(y+1);setFocus(null);}}>다음 층</button></div><p>북쪽 ↑ · X는 오른쪽, Z는 아래쪽 · 완료 {count}층</p><label><input type="checkbox" disabled={!cells.length} checked={!!cells.length&&completed[y]===signature} onChange={e=>onComplete(y,e.target.checked?signature:'')}/> Y={y} 건축 완료</label><div className="guide-grid-wrap"><div className="guide-grid" style={{gridTemplateColumns:`32px repeat(${maxX-minX+1},32px)`}}><span>Z/X</span>{Array.from({length:maxX-minX+1},(_,i)=><span key={`x${i}`}>{minX+i}</span>)}{Array.from({length:maxZ-minZ+1},(_,iz)=>{const z=minZ+iz;return [<span key={`z${z}`}>{z}</span>,...Array.from({length:maxX-minX+1},(_,ix)=>{const x=minX+ix,b=map.get(`${x},${z}`),name=b?placementById.get(b.type)?.name:'빈칸';return <button key={`${x},${z}`} title={`${x}, ${y}, ${z} · ${name}`} aria-label={`${x}, ${y}, ${z} · ${name}`} style={{background:b?placementById.get(b.type)?.color:undefined}} onClick={()=>setFocus(b||null)}>{b?types.indexOf(b.type)+1:'·'}</button>;})];})}</div></div>{focus&&<p role="status">({focus.x}, {focus.y}, {focus.z}) {placementById.get(focus.type)?.name} · {focus.facing||'north'}</p>}<h3>이 층의 재료</h3>{requiredItems(cells).map(r=>{const type=types.find(t=>placementById.get(t)?.id===r.id)!;return <p key={r.id}>{types.indexOf(type)+1}. {placementById.get(type)?.name} <b>{r.count}개</b></p>;})}{!cells.length&&<p>이 층에는 블록이 없습니다.</p>}</div>;
}
